import type {
    User,
    Event,
    Announcement,
    Task,
    HoursEntry,
    Project,
    Document,
} from "./types";

// ============ USERS ============
export const mockUsers: User[] = [
    {
        id: "u1",
        email: "admin@amicus.md",
        password: "admin123",
        name: "Andrei Popescu",
        role: "admin",
        phone: "+373 69 123 456",
        joinDate: "2023-01-15",
        department: "Management",
        bio: "Coordonator principal al organizatiei AMiCUS. Responsabil de gestionarea echipei de voluntari.",
        totalHours: 520,
        tasksCompleted: 87,
        eventsAttended: 45,
    },
    {
        id: "u2",
        email: "maria@amicus.md",
        password: "user123",
        name: "Maria Rusu",
        role: "volunteer",
        phone: "+373 68 234 567",
        joinDate: "2023-06-20",
        department: "Comunicare",
        bio: "Voluntar activ in departamentul de comunicare. Pasionata de social media si PR.",
        totalHours: 180,
        tasksCompleted: 34,
        eventsAttended: 22,
    },
    {
        id: "u3",
        email: "ion@amicus.md",
        password: "user123",
        name: "Ion Ceban",
        role: "volunteer",
        phone: "+373 79 345 678",
        joinDate: "2024-01-10",
        department: "Evenimente",
        bio: "Organizator de evenimente si team leader pentru proiecte comunitare.",
        totalHours: 240,
        tasksCompleted: 45,
        eventsAttended: 30,
    },
    {
        id: "u4",
        email: "elena@amicus.md",
        password: "user123",
        name: "Elena Moraru",
        role: "volunteer",
        phone: "+373 60 456 789",
        joinDate: "2024-03-05",
        department: "Educatie",
        bio: "Trainera si facilitatoare de workshopuri educationale.",
        totalHours: 150,
        tasksCompleted: 28,
        eventsAttended: 18,
    },
    {
        id: "u5",
        email: "vlad@amicus.md",
        password: "user123",
        name: "Vlad Cojocaru",
        role: "volunteer",
        phone: "+373 78 567 890",
        joinDate: "2024-05-15",
        department: "IT",
        bio: "Responsabil de infrastructura digitala si dezvoltarea platformelor online.",
        totalHours: 120,
        tasksCompleted: 22,
        eventsAttended: 12,
    },
    {
        id: "u6",
        email: "diana@amicus.md",
        password: "user123",
        name: "Diana Lungu",
        role: "volunteer",
        phone: "+373 69 678 901",
        joinDate: "2024-07-01",
        department: "Fundraising",
        bio: "Specialist in strangere de fonduri si relatii cu partenerii.",
        totalHours: 90,
        tasksCompleted: 15,
        eventsAttended: 10,
    },
    {
        id: "u7",
        email: "alex@amicus.md",
        password: "user123",
        name: "Alexandru Bivol",
        role: "volunteer",
        phone: "+373 79 789 012",
        joinDate: "2025-01-10",
        department: "Comunicare",
        bio: "Designer grafic si content creator pentru retelele sociale.",
        totalHours: 60,
        tasksCompleted: 10,
        eventsAttended: 5,
    },
];

// ============ EVENTS ============
export const mockEvents: Event[] = [
    {
        id: "e1",
        title: "Adunarea Generala AMiCUS",
        description: "Sedinta anuala cu toti membrii organizatiei pentru evaluarea activitatii si planificarea anului urmator.",
        date: "2026-03-15",
        endDate: "2026-03-15",
        location: "Sala de conferinte, str. Stefan cel Mare 75, Chisinau",
        type: "meeting",
        createdBy: "u1",
        attendees: ["u1", "u2", "u3", "u4", "u5", "u6", "u7"],
        color: "#0891b2",
    },
    {
        id: "e2",
        title: "Training: Leadership pentru Tineri",
        description: "Program de training intensiv pe tema leadership-ului pentru tineri voluntari.",
        date: "2026-03-22",
        endDate: "2026-03-23",
        location: "Centrul de Tineret, str. Puskin 22, Chisinau",
        type: "training",
        createdBy: "u1",
        attendees: ["u2", "u3", "u4", "u5"],
        color: "#059669",
    },
    {
        id: "e3",
        title: "Curatenie Generala in Parcul Valea Morilor",
        description: "Actiune de voluntariat pentru curatenia parcului. Aducem manusi si saci!",
        date: "2026-04-05",
        location: "Parcul Valea Morilor, Chisinau",
        type: "event",
        createdBy: "u1",
        attendees: ["u1", "u2", "u3", "u6", "u7"],
        color: "#d97706",
    },
    {
        id: "e4",
        title: "Workshop: Social Media Marketing",
        description: "Invatam cum sa cream continut atractiv si sa gestionam conturile de social media ale organizatiei.",
        date: "2026-04-12",
        location: "Online - Zoom",
        type: "workshop",
        createdBy: "u1",
        attendees: ["u2", "u5", "u7"],
        color: "#7c3aed",
    },
    {
        id: "e5",
        title: "Gala de Fundraising AMiCUS",
        description: "Eveniment de strangere de fonduri cu prezentarea proiectelor realizate si planificate.",
        date: "2026-04-25",
        location: "Hotel Nobil, str. Columna 22, Chisinau",
        type: "fundraiser",
        createdBy: "u1",
        attendees: ["u1", "u2", "u3", "u4", "u5", "u6", "u7"],
        color: "#dc2626",
    },
    {
        id: "e6",
        title: "Team Building - Excursie la Orheiul Vechi",
        description: "O zi de team building si relaxare la Orheiul Vechi.",
        date: "2026-05-10",
        location: "Orheiul Vechi, Orhei",
        type: "event",
        createdBy: "u1",
        attendees: ["u1", "u2", "u3", "u4", "u5", "u6"],
        color: "#0891b2",
    },
    {
        id: "e7",
        title: "Sedinta de planificare Q3",
        description: "Planificarea activitatilor pentru trimestrul 3 al anului 2026.",
        date: "2026-06-01",
        location: "Biroul AMiCUS, str. Tighina 49, Chisinau",
        type: "meeting",
        createdBy: "u1",
        attendees: ["u1", "u2", "u3"],
        color: "#0891b2",
    },
];

// ============ ANNOUNCEMENTS ============
export const mockAnnouncements: Announcement[] = [
    {
        id: "a1",
        title: "Bun venit in platforma AMiCUS!",
        content: "Dragi voluntari, va anuntam ca platforma noastra de gestionare a fost lansata oficial. Aici puteti gasi toate informatiile necesare despre activitatile organizatiei, task-uri si evenimente. Va rugam sa va completati profilul!",
        createdBy: "u1",
        createdAt: "2026-02-01T10:00:00",
        priority: "high",
        pinned: true,
    },
    {
        id: "a2",
        title: "Inscrierile pentru Training-ul de Leadership sunt deschise",
        content: "Avem placerea de a anunta ca inscrierile pentru Training-ul de Leadership pentru Tineri sunt acum deschise. Training-ul va avea loc pe 22-23 martie. Locurile sunt limitate la 20 de participanti!",
        createdBy: "u1",
        createdAt: "2026-02-10T14:30:00",
        priority: "medium",
        pinned: false,
    },
    {
        id: "a3",
        title: "Modificare program birou",
        content: "Va informam ca incepand cu 1 martie, biroul AMiCUS va fi deschis de luni pana vineri, intre orele 9:00-18:00. In weekenduri, biroul va fi disponibil doar cu programare prealabila.",
        createdBy: "u1",
        createdAt: "2026-02-15T09:00:00",
        priority: "low",
        pinned: false,
    },
    {
        id: "a4",
        title: "Cautam voluntari pentru Gala de Fundraising",
        content: "Echipa de organizare a Galei de Fundraising cauta 10 voluntari pentru a ajuta cu logistica evenimentului din 25 aprilie. Daca esti interesat, contacteaza-l pe Ion Ceban sau Diana Lungu.",
        createdBy: "u1",
        createdAt: "2026-02-17T11:00:00",
        priority: "high",
        pinned: true,
    },
    {
        id: "a5",
        title: "Rezultatele sondajului de satisfactie",
        content: "Multumim tuturor celor care au completat sondajul de satisfactie! Rezultatele arata ca 92% dintre voluntari sunt multumiti de activitatea organizatiei. Vom continua sa imbunatatim experienta voastra!",
        createdBy: "u1",
        createdAt: "2026-02-12T16:00:00",
        priority: "low",
        pinned: false,
    },
];

// ============ TASKS ============
export const mockTasks: Task[] = [
    {
        id: "t1",
        title: "Design afis pentru Gala de Fundraising",
        description: "Crearea unui afis profesional pentru evenimentul de fundraising din aprilie. Trebuie sa includa logo-ul AMiCUS, data, locatia si informatiile de contact.",
        status: "IN_PROGRESS",
        assigneeId: "u7",
        ownerId: "u1",
        dueDate: "2026-03-20",
        createdAt: "2026-02-10T10:00:00",
        priority: "high",
        category: "Design",
    },
    {
        id: "t2",
        title: "Pregatire materiale training Leadership",
        description: "Pregatirea prezentarilor si materialelor handout pentru training-ul de leadership din 22-23 martie.",
        status: "REVIEW",
        assigneeId: "u4",
        ownerId: "u1",
        dueDate: "2026-03-18",
        createdAt: "2026-02-05T09:00:00",
        priority: "high",
        category: "Educatie",
    },
    {
        id: "t3",
        title: "Actualizare pagina Facebook",
        description: "Publicare postari saptamanale pe pagina de Facebook a organizatiei. Minimum 3 postari pe saptamana.",
        status: "IN_PROGRESS",
        assigneeId: "u2",
        ownerId: "u1",
        dueDate: "2026-03-31",
        createdAt: "2026-02-01T08:00:00",
        priority: "medium",
        category: "Comunicare",
    },
    {
        id: "t4",
        title: "Contactare sponsori Gala",
        description: "Contactarea potentialilor sponsori pentru Gala de Fundraising. Lista cu 15 companii a fost trimisa pe email.",
        status: "BLOCKED",
        assigneeId: "u6",
        ownerId: "u1",
        dueDate: "2026-03-25",
        createdAt: "2026-02-08T14:00:00",
        priority: "high",
        category: "Fundraising",
    },
    {
        id: "t5",
        title: "Configurare sistem de ticketing",
        description: "Implementarea unui sistem de ticketing pentru evenimentele organizatiei folosind Google Forms.",
        status: "PLANNED",
        assigneeId: "u5",
        ownerId: "u1",
        dueDate: "2026-04-01",
        createdAt: "2026-02-15T10:00:00",
        priority: "medium",
        category: "IT",
    },
    {
        id: "t6",
        title: "Raport financiar Q1 2026",
        description: "Pregatirea raportului financiar pentru primul trimestru al anului 2026.",
        status: "PLANNED",
        assigneeId: "u6",
        ownerId: "u1",
        dueDate: "2026-04-10",
        createdAt: "2026-02-17T08:00:00",
        priority: "low",
        category: "Administrativ",
    },
    {
        id: "t7",
        title: "Organizare logistica curatenie parc",
        description: "Procurare manusi, saci de gunoi si coordonare transport pentru actiunea de curatenie din parcul Valea Morilor.",
        status: "DONE",
        assigneeId: "u3",
        ownerId: "u1",
        dueDate: "2026-04-03",
        createdAt: "2026-02-12T11:00:00",
        priority: "medium",
        category: "Evenimente",
    },
    {
        id: "t8",
        title: "Recrutare noi voluntari",
        description: "Campanie de recrutare a 10 noi voluntari prin intermediul retelelor sociale si universitatilor din Chisinau.",
        status: "IN_PROGRESS",
        assigneeId: "u2",
        ownerId: "u1",
        dueDate: "2026-04-15",
        createdAt: "2026-02-14T09:00:00",
        priority: "medium",
        category: "HR",
    },
];

// ============ HOURS ENTRIES ============
export const mockHoursEntries: HoursEntry[] = [
    {
        id: "h1",
        volunteerId: "u2",
        date: "2026-02-10",
        hours: 4,
        description: "Gestionare pagina Facebook - creare si publicare postari",
        relatedTaskId: "t3",
        status: "approved",
    },
    {
        id: "h2",
        volunteerId: "u3",
        date: "2026-02-12",
        hours: 6,
        description: "Organizare logistica pentru actiunea de curatenie",
        relatedTaskId: "t7",
        status: "approved",
    },
    {
        id: "h3",
        volunteerId: "u4",
        date: "2026-02-14",
        hours: 5,
        description: "Pregatire prezentari pentru training-ul de Leadership",
        relatedTaskId: "t2",
        status: "approved",
    },
    {
        id: "h4",
        volunteerId: "u5",
        date: "2026-02-15",
        hours: 3,
        description: "Cercetare solutii de ticketing pentru evenimente",
        relatedTaskId: "t5",
        status: "pending",
    },
    {
        id: "h5",
        volunteerId: "u6",
        date: "2026-02-13",
        hours: 4,
        description: "Intocmire lista sponsori si draft emailuri de contactare",
        relatedTaskId: "t4",
        status: "approved",
    },
    {
        id: "h6",
        volunteerId: "u7",
        date: "2026-02-16",
        hours: 7,
        description: "Design afis Gala de Fundraising - prima varianta",
        relatedTaskId: "t1",
        status: "pending",
    },
    {
        id: "h7",
        volunteerId: "u2",
        date: "2026-02-15",
        hours: 3,
        description: "Participare la sedinta de planificare echipa comunicare",
        relatedEventId: "e1",
        status: "approved",
    },
    {
        id: "h8",
        volunteerId: "u3",
        date: "2026-02-17",
        hours: 2,
        description: "Coordonare voluntari pentru curatenia din parc",
        relatedEventId: "e3",
        status: "pending",
    },
    {
        id: "h9",
        volunteerId: "u4",
        date: "2026-02-16",
        hours: 3,
        description: "Pregatire handout-uri pentru training",
        relatedTaskId: "t2",
        status: "rejected",
        adminNote: "Numarul de ore pare prea mare pentru aceasta sarcina. Va rog sa corectati.",
    },
    {
        id: "h10",
        volunteerId: "u2",
        date: "2026-02-17",
        hours: 5,
        description: "Campanie de recrutare - postari pe social media",
        relatedTaskId: "t8",
        status: "pending",
    },
];

// ============ PROJECTS ============
export const mockProjects: Project[] = [
    {
        id: "p1",
        name: "Gala de Fundraising 2026",
        description: "Organizarea galei anuale de strangere de fonduri. Obiectiv: 50,000 MDL.",
        startDate: "2026-02-01",
        endDate: "2026-04-25",
        status: "active",
        leadId: "u1",
        memberIds: ["u1", "u2", "u3", "u6", "u7"],
        progress: 35,
    },
    {
        id: "p2",
        name: "Programul de Leadership pentru Tineri",
        description: "Serie de training-uri si workshopuri pe tema leadershipului destinata tinerilor din Chisinau.",
        startDate: "2026-01-15",
        endDate: "2026-06-30",
        status: "active",
        leadId: "u4",
        memberIds: ["u1", "u4", "u3"],
        progress: 45,
    },
    {
        id: "p3",
        name: "Digitalizare AMiCUS",
        description: "Migrarea proceselor interne ale organizatiei catre platforma digitala.",
        startDate: "2025-11-01",
        endDate: "2026-03-31",
        status: "active",
        leadId: "u5",
        memberIds: ["u1", "u5", "u7"],
        progress: 80,
    },
    {
        id: "p4",
        name: "Curatenie de Primavara 2026",
        description: "Actiune de voluntariat pentru curatenia parcurilor din Chisinau.",
        startDate: "2026-03-15",
        endDate: "2026-04-15",
        status: "planning",
        leadId: "u3",
        memberIds: ["u1", "u2", "u3", "u6"],
        progress: 15,
    },
    {
        id: "p5",
        name: "Campania de Recrutare Iarna 2026",
        description: "Campanie de recrutare a 30 de noi voluntari prin intermediul universitatilor.",
        startDate: "2025-12-01",
        endDate: "2026-02-28",
        status: "completed",
        leadId: "u2",
        memberIds: ["u1", "u2", "u7"],
        progress: 100,
    },
];

// ============ DOCUMENTS ============
export const mockDocuments: Document[] = [
    {
        id: "d1",
        name: "Regulament Intern AMiCUS 2026",
        type: "pdf",
        uploadedBy: "u1",
        uploadedAt: "2026-01-15T10:00:00",
        size: "2.4 MB",
        category: "policy",
        url: "#",
    },
    {
        id: "d2",
        name: "Raport Anual 2025",
        type: "pdf",
        uploadedBy: "u1",
        uploadedAt: "2026-01-20T14:00:00",
        size: "5.1 MB",
        category: "report",
        url: "#",
    },
    {
        id: "d3",
        name: "Template Contract Voluntariat",
        type: "doc",
        uploadedBy: "u1",
        uploadedAt: "2026-01-10T09:00:00",
        size: "156 KB",
        category: "template",
        url: "#",
    },
    {
        id: "d4",
        name: "Manual Identitate Vizuala",
        type: "pdf",
        uploadedBy: "u1",
        uploadedAt: "2025-12-01T11:00:00",
        size: "8.3 MB",
        category: "policy",
        url: "#",
    },
    {
        id: "d5",
        name: "Prezentare Training Leadership",
        type: "doc",
        uploadedBy: "u4",
        uploadedAt: "2026-02-14T16:00:00",
        size: "3.7 MB",
        category: "training",
        url: "#",
    },
    {
        id: "d6",
        name: "Buget Gala Fundraising 2026",
        type: "spreadsheet",
        uploadedBy: "u1",
        uploadedAt: "2026-02-08T10:00:00",
        size: "420 KB",
        category: "report",
        url: "#",
    },
    {
        id: "d7",
        name: "Template Raport Activitate Lunara",
        type: "doc",
        uploadedBy: "u1",
        uploadedAt: "2026-01-05T08:00:00",
        size: "98 KB",
        category: "template",
        url: "#",
    },
    {
        id: "d8",
        name: "Ghid de Bune Practici Voluntariat",
        type: "pdf",
        uploadedBy: "u1",
        uploadedAt: "2025-11-15T13:00:00",
        size: "1.8 MB",
        category: "training",
        url: "#",
    },
];
